# Generated by Django 3.1 on 2022-10-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('video_short_description', models.CharField(max_length=255)),
                ('video_uplode', models.FileField(upload_to='videos_uploaded')),
            ],
        ),
    ]
