# Generated by Django 4.1.7 on 2023-03-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('video_short_description', models.CharField(max_length=255)),
                ('video_uplode', models.FileField(upload_to='videos_uploaded')),
            ],
        ),
    ]
