# Generated by Django 4.1.7 on 2023-03-05 10:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('flag_image', models.ImageField(upload_to='flag_images')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.IntegerField(choices=[(1, 'Business'), (2, 'Tourist'), (3, 'Medical'), (3, 'Student')])),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('passport_number', models.CharField(max_length=100)),
                ('nid_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='NID Number')),
                ('occupation', models.IntegerField(choices=[(1, 'Student'), (2, 'Government Job'), (3, 'Private Job'), (4, 'Business'), (5, 'Teacher'), (6, 'Doctor'), (7, 'Other')])),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('date_of_birth', models.DateField()),
                ('where_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_from', to='services_app.country', verbose_name='Where am I From?')),
                ('where_going', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_going', to='services_app.country', verbose_name='Where am I Going?')),
                ('which_country_passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='which_country_passport', to='services_app.country')),
            ],
        ),
    ]
