# Generated by Django 4.1.7 on 2023-03-05 10:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
