# Generated by Django 3.1 on 2023-03-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_alter_country_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_type', models.CharField(max_length=250)),
                ('flying_from', models.CharField(max_length=250)),
                ('flying_to', models.CharField(max_length=250)),
                ('departing', models.CharField(max_length=250)),
                ('returning', models.CharField(max_length=250)),
                ('adults', models.CharField(max_length=250)),
                ('children', models.CharField(max_length=250)),
                ('travel_class', models.CharField(max_length=250)),
            ],
        ),
    ]
