# Generated by Django 3.1 on 2023-03-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_auto_20230227_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='nid_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
