# Generated by Django 4.1.7 on 2023-03-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('arrivals', models.DateField()),
                ('leaving', models.DateField()),
                ('tour_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package_app.packages', verbose_name='Tour Place')),
            ],
        ),
    ]
