# Generated by Django 3.1 on 2022-10-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_place', models.CharField(max_length=255, verbose_name='Enter Tour Place')),
                ('tour_place_description', models.TextField(verbose_name='Enter Tour Place Description')),
                ('packages_image', models.ImageField(upload_to='packages_images', verbose_name='Image')),
                ('package_old_price', models.IntegerField(blank=True, null=True)),
                ('package_new_price', models.IntegerField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
