# Generated by Django 4.1.7 on 2023-03-07 06:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='tour_place_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
